### ISSUE TITLE
So...how do I import my file?

### ISSUE THREAD

**Issue by eeleclair** [BrianOSullivanGit/vcfView#2]
I installed R, Rstudio and ran the file 'app.R'.  It downloaded a million things and then finished.  So now I have a screen that looks like this, 

<img width="1035" alt="Screen Shot 2020-12-09 at 8 02 40 PM" src="https://user-images.githubusercontent.com/75765935/101711636-97e80e00-3a59-11eb-94db-538ca377bf5e.png">

...but how do I get to the screen that looks like this?

<img width="879" alt="Screen Shot 2020-12-09 at 8 02 14 PM" src="https://user-images.githubusercontent.com/75765935/101711652-a33b3980-3a59-11eb-9dfa-f0dbbaf4dc8a.png">

**Comment by BrianOSullivanGit** [comment]
Hi eeleclair,

If you click runApp (top right) it should bring up an application window prompting you to load a VCF file. You can load one of the ones in the vignette or one your own. Any problems please let me know & we will resolve them.

Thanks for trying it out!

Brian
